//cstmService.js
import {StyleSheet} from 'react-native'
import {css,deviceWidth} from 'init'

const style = StyleSheet.create({
    ctnr:{
    },
    actnr:{
        display:'flex',
	justifyContent:'space-between',
	borderBottomWidth:1,
	borderColor:'#dedede',
        backgroundColor:'#fff',
    },
    label:{
	marginLeft:12,
	marginTop:12,
	marginBottom:5,
	fontSize:css.f2,
	color:'#333'
    },
    info:{
	marginLeft:12,
	marginBottom:12,	
	fontSize:css.f1/14*12,	
	color:'#666'
    },
    listViewStyle:{
        flexDirection:'column',
    },
    cdbg:{
	backgroundColor:'#4283a1',
	height:45*deviceWidth/100,
	display:'flex',
	justifyContent:'space-around'
    },
    cdhd:{
	marginLeft:12,
	color:'#eee',
	fontSize:css.f1
    },
    cdsm:{
	color:'#eee',
	fontSize:css.f1/14*36,
	textAlign:'center'
    },
    cdid:{
	marginLeft:12,
	fontSize:css.f1,
	color:'#eee',	
    },
    wdbg:{
	display:'flex',
	justifyContent:'center',
	alignItems:'center',
	height:deviceWidth/100*20,
	backgroundColor:'#fff',
	marginBottom:12
    },
    wdbtn:{
	backgroundColor:css.color,
	display:'flex',
	justifyContent:'center',
	width:css.f1/14*56,
	borderRadius:5,
	marginBottom:5
    },
    wdtext:{
	textAlign:'center',
	margin:5,
	fontSize:css.f2,
	color:'#eee',
    },
    wdinfo:{
	marginTop:12,
	fontSize:css.f1,
	color:'#999'	
    }
})

export default style
