//cstmService.js
import {StyleSheet} from 'react-native'


const style = StyleSheet.create({
    ctnr:{
    },
    actnr:{
        display:'flex',
	justifyContent:'space-between',
	borderBottomWidth:1,
	borderColor:'#dedede',
        backgroundColor:'#fff',
    },
    label:{
	marginLeft:3.8,
	marginTop:3.2,
	marginBottom:1.2,
	fontSize:5,
	color:'#333'
    },
    info:{
	marginLeft:3.8,
	marginBottom:3.2,	
	fontSize:3.8,	
	color:'#666'
    },
    listViewStyle:{
        flexDirection:'column',
    },
    cdbg:{
	backgroundColor:'#4283a1',
	height:38,
	display:'flex',
	justifyContent:'space-around'
    },
    cdhd:{
	marginLeft:3.8,
	color:'#eee',
	fontSize:3.8
    },
    cdsm:{
	color:'#eee',
	fontSize:12,
	textAlign:'center'
    },
    cdid:{
	marginLeft:3.8,
	fontSize:5,
	color:'#eee',	
    },
    wdbg:{
	display:'flex',
	justifyContent:'center',
	alignItems:'center',
	height:20,
	backgroundColor:'#fff',
	marginBottom:3.8
    },
    wdbtn:{
	backgroundColor:'#4283a1',
	display:'flex',
	justifyContent:'center',
	width:20,
	height:8,
	borderRadius:5,
	marginBottom:1
    },
    wdtext:{
	textAlign:'center',
	fontSize:5,
	color:'#eee',
    },
    wdinfo:{
	fontSize:3,
	color:'#999'	
    }
})

export default style
